/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TUPLAS_H_RPCGEN
#define _TUPLAS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct set_modify_args {
	int key;
	char *value1;
	value2_t value2;
	Coord value3;
};
typedef struct set_modify_args set_modify_args;

struct get_value_res {
	int status;
	char *value1;
	value2_t value2;
	Coord value3;
};
typedef struct get_value_res get_value_res;

#define TUPLAS_PROG 0x20000001
#define TUPLAS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DESTROY 0
extern  int * destroy_1(void *, CLIENT *);
extern  int * destroy_1_svc(void *, struct svc_req *);
#define DELETE_KEY 1
extern  int * delete_key_1(int *, CLIENT *);
extern  int * delete_key_1_svc(int *, struct svc_req *);
#define EXIST 2
extern  int * exist_1(int *, CLIENT *);
extern  int * exist_1_svc(int *, struct svc_req *);
#define SET_VALUE 3
extern  int * set_value_1(set_modify_args *, CLIENT *);
extern  int * set_value_1_svc(set_modify_args *, struct svc_req *);
#define GET_VALUE 4
extern  get_value_res * get_value_1(int *, CLIENT *);
extern  get_value_res * get_value_1_svc(int *, struct svc_req *);
#define MODIFY_VALUE 5
extern  int * modify_value_1(set_modify_args *, CLIENT *);
extern  int * modify_value_1_svc(set_modify_args *, struct svc_req *);
extern int tuplas_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DESTROY 0
extern  int * destroy_1();
extern  int * destroy_1_svc();
#define DELETE_KEY 1
extern  int * delete_key_1();
extern  int * delete_key_1_svc();
#define EXIST 2
extern  int * exist_1();
extern  int * exist_1_svc();
#define SET_VALUE 3
extern  int * set_value_1();
extern  int * set_value_1_svc();
#define GET_VALUE 4
extern  get_value_res * get_value_1();
extern  get_value_res * get_value_1_svc();
#define MODIFY_VALUE 5
extern  int * modify_value_1();
extern  int * modify_value_1_svc();
extern int tuplas_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_set_modify_args (XDR *, set_modify_args*);
extern  bool_t xdr_get_value_res (XDR *, get_value_res*);

#else /* K&R C */
extern bool_t xdr_set_modify_args ();
extern bool_t xdr_get_value_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TUPLAS_H_RPCGEN */
