/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Entregable3/tuplas.h"

bool_t
xdr_set_modify_args (XDR *xdrs, set_modify_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_value2_t (xdrs, &objp->value2))
		 return FALSE;
	 if (!xdr_Coord (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_value_res (XDR *xdrs, get_value_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_value2_t (xdrs, &objp->value2))
		 return FALSE;
	 if (!xdr_Coord (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
